### ISSUE TITLE
Release binary broken

### ISSUE THREAD

**Issue by devalru** [ekristen/dns-proxy#54]
Downloaded the latest win release. Executable terminates with error:

c:\Users\****\Downloads>dns-proxy-win.exe
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:221:7)
    at Object.fs.watchFile (fs.js:1471:25)
    at Object.<anonymous> (C:\snapshot\dns-proxy\dns-proxy.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1298:12)

**Comment by ekristen** [comment]
I suspect it's because no configuration file is being passed and I'm not catching that error on windows.

Try creating a configuration file and specify using --config

**Comment by devalru** [comment]
> Try creating a configuration file and specify using --config

Thx, works now with JSON valid configuration:

./dns-proxy-win.exe --config ./dns-proxy-config.json


Content of configuration file:

{
  "nameservers": [
    "10.11.1.11"
  ],

  "domains": {
    "*.testing": "10.1.103.255",
    "*.apps-crc.testing": "10.1.103.255"
    }
}
